### PR TITLE
checking for degenerated splines on input port

### PR DESCRIPTION
**Pull request by leifole**
checking for degenerated splines before switching in FOLLOWING_TRAJECTORY state. Added DEGENERATED_TRAJECTORY state for that case.

### CODE REVIEW

**Comment by ajishbabu** [comment]
@leifole @maltewi do you guys use this regularly? If so could you take over the maintenance of component and the library? I am not currently using it and hence cannot really test any of it.

**Comment by leifole** [comment]
Nope, I'm not using it at all right now and also not in the foreseeable future. It's just something I stumbled upon that was not merged into master after the Utah field trials

**Comment by Rauldg** [comment]
@ajishbabu, @leifole Is there no maintainer for this package? We need to use it in ADE.

Can this PR be merged? Should it be tested somehow before? I think that it has been used in Morocco (@maltewi?) and Utah. 

Do you have any suggestion on who should take over maintenance? I could take over, but honestly, I have mostly user experience with it.

**Comment by maltewi** [comment]
We did not use it in morocco since trajectory following was part of our partners work, but I had the same problem on Artemis.

I used this version of dealing with the same problem on Artemis: #3

I did not put additional effort on getting this or #3 merged since in my application the problem is solve by https://github.com/rock-planning/planning-motion_planning_libraries/pull/14 (merged). There was a bug in the planner: It wrote degenerated splines to the output port if it actually wanted the rover to stay at its place.

Since that fix the issue reported did not occur any more. Nevertheless checking of the input data is feasible for further processing is a good thing (that means I have no principle objections with merging this PR or #3 <--- for clarity: that statement does not mean I made a review and say it's safe to merge).

**Comment by skasperski** [comment]
So if I understand it correctly, this is a specific fix for a bug in the trajectory-generation, which caused the generation of one-point-trajectories. Is this the only way a trajectory can be degenerated? Maybe it would be better to have a more general validity check of trajectories (preferably done in its own method), which is used to check each input and can be enhanced when other types of invalid input are discovered.

**Comment by leifole** [comment]
> Maybe it would be better to have a more general validity check of trajectories (preferably done in its own method), which is used to check each input and can be enhanced when other types of invalid input are discovered.

I agree, do you want to prepare a pull request? Would it hurt to merge this PR in the meantime?

**Comment by skasperski** [comment]
> Would it hurt to merge this PR in the meantime?

No, I don't think so. Has someone verified that it builds with master?

**Comment by skasperski** [comment]
The changes were moved to #11 because this became incompatible with master.

**Pull request closed without merging**
